#!/bin/bash
sed -i 's/msgstr "Lucky"/msgstr "反向代理"/g' package/luci-app-lucky/po/zh-cn/lucky.po
sed -i 's/services/vpn/g' $(grep -rl 'services' package/luci-app-lucky)
echo -----------------END-------------------
