#!/bin/bash
sed -i 's/msgstr "MosDNS"/msgstr "DNS 加速"/g' package/luci-app-mosdns/po/zh_Hans/mosdns.po
sed -i 's/\bservices\b/vpn/g' $(grep -rl '\bservices\b' package/luci-app-mosdns)
echo -----------------START-------------------
