#!/bin/bash
sed -i '/msgid "Pass Wall"/{n;s/PassWall/翻越长城/;}' package/luci-app-passwall/po/zh_Hans/passwall.po
sed -i 's/\bservices\b/vpn/g' $(grep -rl '\bservices\b' package/luci-app-passwall)
echo -----------------START-------------------
