#!/bin/bash
sed -i 's/msgstr "MosDNS"/msgstr "DNS 加速"/g' package/luci-app-mosdns/po/zh_Hans/mosdns.po
sed -i 's/services/vpn/g' $(grep -rl 'services' package/luci-app-mosdns)
echo -----------------END-------------------
